scrape_configs:
 - job_name: file
   file_sd_configs:
    - files:
       - '*.json'
   relabel_configs:
      source_labels: [team]
      regex: monitoring
      replacement: monitor
      target_label: team
      action: replace
